### ISSUE TITLE
GitHub setup

### ISSUE THREAD

**Issue by RommelTJ** [rockthejvm/udemy-akka-persistence-starter#1]
GitHub setup and fixing IDE stuff

**Comment by daniel-ciocirlan** [comment]
Which stuff are you referring to?

**Comment by RommelTJ** [comment]
I'm so sorry, I thought I was writing an issue in my forked repo. Didn't mean to write it here. Closing.

**Comment by daniel-ciocirlan** [comment]
No problem.
